import type { Metadata } from "next"
import { Providers } from "./providers"
import { oswald } from "../fonts/fonts"

import "./globals.css"

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
}

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode
}>) {
	return (
		<html lang="en">
			<body className={`${oswald.className} antialiased w-screen h-screen`}>
				<Providers>{children}</Providers>
			</body>
		</html>
	)
}
