export const fakeUsers = [
	{
		name: "John Doe",
		email: "jhon@example.com",
		password: "123456",
		lastLogin: new Date(),
		registrationTime: new Date(),
		status: "Active",
	},
	{
		name: "Jane Smith",
		email: "jane@example.com",
		password: "password123",
		lastLogin: new Date(),
		registrationTime: new Date(),
		status: "Active",
	},
	{
		name: "Alice Johnson",
		email: "alice@example.com",
		password: "qwerty",
		lastLogin: new Date(),
		registrationTime: new Date(),
		status: "Active",
	},
	{
		name: "Bob Williams",
		email: "bob@example.com",
		password: "pass123",
		lastLogin: new Date(),
		registrationTime: new Date(),
		status: "Active",
	},
	{
		name: "Emily Davis",
		email: "emily@example.com",
		password: "password",
		lastLogin: new Date(),
		registrationTime: new Date(),
		status: "Active",
	},
	{
		name: "Michael Brown",
		email: "michael@example.com",
		password: "abc123",
		lastLogin: new Date(),
		registrationTime: new Date(),
		status: "Active",
	},
]
